### ISSUE TITLE
Any Plan to release the code？

### ISSUE THREAD

**Issue by cjcio** [YihongT/ITINERA#1]
Nice work! Is there any plan to release the inference code？

**Comment by wzk1015** [comment]
Hi, thanks for the interest. We plan to release the code and dataset in the next few weeks.

**Comment by Luyunfei0728** [comment]
Could you please let me know when the code will be released？

**Comment by ShenYuhan** [comment]
May I ask if there is a timeline for releasing the code?

**Comment by YihongT** [comment]
Hi all, please check out our latest updates for the released code and example data. 

I’ll close this issue now. For any further inquiries, please open a new one. 

Thanks again for your interest.
