### ISSUE TITLE
Unable to Call OpenAI API for Embedding Model; Seeking Alternatives

### ISSUE THREAD

**Issue by Luyunfei0728** [YihongT/ITINERA#3]
I'm currently facing an issue with my project where the embedding model is unable to call the OpenAI API. I have tried downloading the ada-002 model, but it does not seem to work as expected. Could you please suggest any alternative models that I could use?I have tried switching to a different embedding model, but the dimensions do not match the required 1536. Could you please advise where I can make the necessary adjustments?
![Snipaste_2024-11-12_11-24-33](https://github.com/user-attachments/assets/3c70fbd1-b51e-4adf-a1ac-96dfa4bee6c4)

**Comment by Luyunfei0728** [comment]
> 我目前在项目中遇到嵌入模型无法调用 OpenAI API 的问题。我尝试下载 ada-002 模型，但它似乎没有按预期工作。您能否推荐我可以使用的任何替代模型？

![微信图片_20241112101805](https://github.com/user-attachments/assets/eac42cbb-acad-422d-95e8-125c7ec09a66)

**Comment by YihongT** [comment]
Hi, the example embeddings we provided were generated with the "text-embedding-3-small" model, which produces embeddings with a dimension of 1536. Note that you need to use the same embedding model for both user query and POI embeddings. The OpenAI model is not available for download, so you can only make API calls to access it. You may try generating embeddings with your custom model for POIs using the context column in the example data, ensuring you use the same model for user query embeddings. Thank you.
