### ISSUE TITLE
Request for Access to Experimental Dataset and Evaluation Code

### ISSUE THREAD

**Issue by Luyunfei0728** [YihongT/ITINERA#4]
I am currently exploring the research presented in your recent publication, could you kindly share the dataset and the evaluation code that were used in your experiments? Access to these resources would greatly aid in replicating your results and potentially extending the research.

**Comment by YihongT** [comment]
Hi, the data used in our experiments adheres to strict user privacy policies. We can use this data to improve our system and optimize user experience, but we do not share it. However, you can prepare your own data in a format similar to the example dataset we provided to run our system. Thank you.
